### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by kernelsmith** [jtsymon/cve_monitor#1]
Hi @jtsymon, I just wanted to ask if you're open to pull requests? I don't have any particular functionality to give yet, but there are some spots where I could make the code more in line with the Ruby Style Guide. However, I don't want to a) waste anyone's time and b) have any PR be taken as an insult or mean-spirited. I review a decent amount of Ruby code so I can't help spotting certain things, it's not something I intended to do.  Example:

```Ruby
if var.nil?
```
should generally be `if var` unless var is specifically a boolean and you want to distinguish between nil and false

I know it's been a while since you wrote this, but I love the idea and your gem. I'm interested in helping where I can

Josh

**Comment by jtsymon** [comment]
Hi Josh,

I haven't touched this in a long time, but I'm happy if you can get any use out of it or have any improvements to make.
